version: "3.8"

services:
 rabin.angular-project:
    container_name: rabin.angular-project-container
    build:
      context: ./              
      dockerfile: Dockerfile   
    ports:
      - "9999:8080"                           


    restart: on-failure